var $patches_opt = {
    "build.source":"full",
    "build.registry.software":"merge",
    "build.catalog":"auto",
    "build.wow64support":true,
    "account.admin_enabled":false,
    "account.autologon_countdown":5,
    "account.admin_screen":"wallpaper",
    "system.darktheme":false,
    "theme.title_color":"1",
    "config.fbwf.cache":"128GB",
    "config.computername":"EDGELES",
    "system.workgroup":"WORKGROUP",
    "system.high_compatibility":true,
    "shell.app":"explorer",
    "tweak.shortcut.noarrow":true,
    "tweak.shortcut.nosuffix":true,
    "component.MMC":true,
    "component.DWM":true,
    "component.vcruntime":true,
    "component.mspaint":true,
    "component.winphotoviewer":true,
    "IE.x64_component":"x64+x86",
    "IE.custom_settings":true,
    "IE.home_page":"about:blank",
    "network.function_discovery":true,
    "network.builtin_drivers":true,
    "slim.winboot":false,
    "build.cmd_mode":false,
    "build.cmd_mode_code":"MODE 150,9999",
    "build.registry.system_driverdatabase":"merge",
    "build.registry.drivers":"merge",
    "account.localized_admin_name":"Administrator",
    "account.custom_admin_name":"Administrator",
    "adk.wpe_path":"C:\\Program Files (x86)\\Windows Kits\\10\\Assessment and Deployment Kit\\Windows Preinstallation Environment",
    "adk.lang":"-",
    "desktop.iconsize":"48",
    "shell.use_theme_color":true,
    "shell.startmenu":"StartAllBack",
    "SIB.version":"*",
    "SIB.programs.flyout":false,
    "policy.lmcompatlevel":"1",
    "network.trayicon":true,
    "network.full_functional":true,
    "network.type_builtin_drivers":"default",
    "component.dsmsvc":true,
    "MTP.mtphelper":"mtpHelper.sys",
    "IME.indicator":true,
    "IME.system_ime":true,
    "IME.ms_pinyin":true,
    "IME.ms_Phonetic":true,
    "component.notepad":true,
    "7-zip.selected_assoc_exts":"7z,zip,rar,vhd,wim,swm",
    "material.location":"X:",
    "material.load_mode":"auto",
    "PEMApp.chrome":true,
    "PEMApp.chrome.type":"INST",
    "PEMApp.chrome.dl_url":"https://dl.google.com/release2/chrome/AMQFLHv8Muh_ExYptfSwv2g_81.0.4044.113/81.0.4044.113_chrome_installer.exe",
    "mycustom.theme_id":"1",
    "slim.mui":true,
    "slim.winre_sources":true,
    "slim.font.mingliu":true,
    "slim.wbem_repository":true,
    "slim.speech":true,
    "slim.hive_drivers":true,
    "slim.hive_software":true,
    "slim.hive_system":true,
    "slim.hive_components":true,
    "vbox.version":"auto",
    "shell.wallpaper":"C:\\Users\\Administrator\\Desktop\\Edgeless\\wp.jpg",
    "build.preprocess_wim":false,
    "build.mount_wim_action":"built_in",
    "build.load_hive":true,
    "build.precommit_wim":true,
    "build.commit_wim_action":"built_in",
    "build.custom_iso":true,
    "build.preprocess_wim_script":"_00-Ô¤´¦ÀíWIMÓ³Ïñ.bat",
    "build.mount_wim_script":"_10-¹ÒÔØWIMÓ³Ïñ.bat",
    "build.precommit_wim_script":"_80-Ô¤Ìá½»WIMÓ³Ïñ.bat",
    "build.commit_wim_script":"_90-±£´æWIMÓ³Ïñ.bat",
    "component.taskmgr":true,
    "component.bitlocker":true,
    "component.search":true,
    "patch.drvinst":false,
    "shell.light_theme":true,
    "shell.show_thisPC":true,
    "shell.show_recyclebin":true,
    "shell.taskbar.combine":"never",
    "shell.fix.showDesktop":true,
    "shell.ui.resolution":true,
    "shell.clockarea.event":true,
    "shell.system.property":true,
    "shell.shortcut.ocf":true,
    "shell.fix.fullscreen":true,
    "component.PPPoE":true,
    "network.hide_system_tray_icon":false,
    "network.networklist_and_sharecenter":true,
    "audio.win_events":"all",
    "audio.hide_system_tray_icon":false,
    "component.MTP":true,
    "component.RNDIS":true,
    "component.printer":false,
    "component.bluetooth":true,
    "component.camera":true,
    "IME.ms_wubi":false,
    "IME.ms_Quick":false,
    "IME.ms_Cangjie":false,
    "IME.cht_DaYi":false,
    "IME.cht_Array":false,
    "component.wordpad":false,
    "component.snippingtool":true,
    "component.accessibility":false,
    "component.MSI":true,
    "component.netfx":true,
    "component.opengl":true,
    "component.directx":true,
    "appcompat.property_page":false,
    "appcompat.assistant":false,
    "loader.name":"pecmd",
    "loader.PEMaterial":"PEMaterial",
    "build.registry.system":false,
    "build.full_catalog":false,
    "system.power.off_disp_bat":0,
    "system.power.off_disp_plug":0,
    "system.power.off_disk_bat":0,
    "system.power.off_disk_plug":0,
    "system.power.dis_usb_suspend_bat":true,
    "system.power.dis_usb_suspend_plug":true,
    "system.volume_level":50,
    "system.volume_mute":false,
    "system.numlock":true,
    "account.SYSTEM_logon_pass":"",
    "account.admin_logon_pass":"",
    "account.admin_password":"",
    "account.admin_autologon":true,
    "account.precreate_admin_profile":false,
    "iso.attended_boot":false,
    "iso.edit_bcd":true,
    "iso.loading_progress":true,
    "iso.x_exFAT":false,
    "custom.restart_explorer_menu":false,
    "custom.restart_explorer_item":"ÖØÆô×ÀÃæ½ø³Ì",
    "custom.show_cmd_menu":false,
    "slim.ieframedll":false,
    "slim.jscript":false,
    "slim.hta":false,
    "slim.wmi":false,
    "slim.small_fonts":false,
    "slim.small_imageresdll":false,
    "slim.safe":false,
    "slim.extra":false,
    "slim.hive":false,
    "mstsc.enable_credssp_support":false,
    "component.termservice":false,
    "imdisk.ramdisk":false,
    "imdisk.drive_letter":"B:",
    "imdisk.disk_size":"2048",
    "winxshell.ui_volume.startup":false,
    "winxshell.ui_volume.no_beep":false,
    "winxshell.ui_wifi.startup":false,
    "_._._":""
}

function patches_state_init() {
    check_tree_node("_CustomFiles_");
    open_tree_node("_CustomFiles_");
    check_tree_node("00-Configures");
    open_tree_node("00-Configures");
    uncheck_tree_node("01-Components/00-Boot2WinRE");
    check_tree_node("01-Components/00-Shell");
    open_tree_node("01-Components/00-Shell");
    check_tree_node("01-Components/02-Network");
    check_tree_node("01-Components/03-Audio");
    select_tree_node("01-Components/03-Audio");
    check_tree_node("01-Components/CredDialog");
    check_tree_node("01-Components/Devices and Printers");
    check_tree_node("01-Components/IME");
    uncheck_tree_node("01-Components/Internet Explorer");
    uncheck_tree_node("01-Components/Remote Desktop");
    uncheck_tree_node("01-Components/Windows Media Player");
    check_tree_node("01-Components/za-Accessories");
    check_tree_node("01-Components/zh-RuntimeKits");
    open_tree_node("01-Components");
    check_tree_node("01-Drivers");
    check_tree_node("02-Apps/7-Zip");
    uncheck_tree_node("02-Apps/Defraggler");
    uncheck_tree_node("02-Apps/Explorer++");
    uncheck_tree_node("02-Apps/HotSwap");
    check_tree_node("02-Apps/ImDisk");
    check_tree_node("02-Apps/PENetwork");
    uncheck_tree_node("02-Apps/yong_IME");
    open_tree_node("02-Apps");
    check_tree_node("02-PEMaterial/00-Collection");
    check_tree_node("02-PEMaterial/01-Maintenance");
    check_tree_node("02-PEMaterial/02-Network");
    uncheck_tree_node("02-PEMaterial/03-Media");
    uncheck_tree_node("02-PEMaterial/04-OfficeApps");
    uncheck_tree_node("02-PEMaterial/05-Entertainment");
    uncheck_tree_node("02-PEMaterial/10-Others");
    open_tree_node("02-PEMaterial");
    uncheck_tree_node("10-MyCustom/00-MyLoader.LINK");
    check_tree_node("10-MyCustom/00-MySystem.LINK");
    uncheck_tree_node("10-MyCustom/01-MyDrivers.LINK");
    uncheck_tree_node("10-MyCustom/10-MyApps.LINK");
    uncheck_tree_node("10-MyCustom/11-MyMaterial.LINK");
    open_tree_node("10-MyCustom/11-MyMaterial.LINK");
    check_tree_node("10-MyCustom/MyContextMenu.LINK");
    check_tree_node("10-MyCustom/MyStartMenu.LINK");
    check_tree_node("10-MyCustom/MyTheme.LINK");
    open_tree_node("10-MyCustom.LINK");
    check_tree_node("za-Slim");
    uncheck_tree_node("za-SlimUltra");
    uncheck_tree_node("zy-Test");
    check_tree_node("zz-ISO");
    check_tree_node("zz-Utils");
    open_tree_node("zz-Utils");
}
