rem 增加文件
call AddFiles %0 :end_files
goto :end_files

\Windows\INF\LSM
\Windows\INF\PERFLIB
\Windows\INF\RemoteAccess
\Windows\INF\TAPISRV
\Windows\INF\acxhdaudiop.inf
\Windows\INF\athw8x.inf
\Windows\INF\b57nd60a.inf
\Windows\INF\bcmdhd64.inf
\Windows\INF\bcmwdidhdpcie.inf
\Windows\INF\bda.inf
\Windows\INF\c_apo.inf
\Windows\INF\c_avc.inf
\Windows\INF\c_linedisplay.inf
\Windows\INF\c_media.inf
\Windows\INF\c_modem.inf
\Windows\INF\c_net.inf
\Windows\INF\c_netclient.inf
\Windows\INF\c_netdriver.inf
\Windows\INF\c_netservice.inf
\Windows\INF\c_nettrans.inf
\Windows\INF\compositebus.inf
\Windows\INF\dc21x4vm.inf
\Windows\INF\e2xw10x64.inf
\Windows\INF\gameport.inf
\Windows\INF\intelpep.inf
\Windows\INF\ipoib6x.inf
\Windows\INF\kdnic.inf
\Windows\INF\ks.inf
\Windows\INF\kscaptur.inf
\Windows\INF\ksfilter.inf
\Windows\INF\lltdio.inf
\Windows\INF\mlx4_bus.inf
\Windows\INF\modemcsa.inf
\Windows\INF\mrvlpcie8897.inf
\Windows\INF\msdri.inf
\Windows\INF\mstape.inf
\Windows\INF\msux64w10.inf
\Windows\INF\mwlu97w8x64.inf
\Windows\INF\ndiscap.inf
\Windows\INF\ndisimplatform.inf
\Windows\INF\ndisimplatformmp.inf
\Windows\INF\ndisuio.inf
\Windows\INF\net*.inf
\Windows\INF\nulhpopr.inf
\Windows\INF\nulhprs8.inf
\Windows\INF\rdpbus.inf
\Windows\INF\rdvgwddmdx11.inf
\Windows\INF\rndiscmp.inf
\Windows\INF\rspndr.inf
\Windows\INF\rt640x64.inf
\Windows\INF\rtux64w10.inf
\Windows\INF\rtwlanu_oldIC.inf
\Windows\INF\tsusbhub.inf
\Windows\INF\urschipidea.inf
\Windows\INF\urssynopsys.inf
\Windows\INF\usbcir.inf
\Windows\INF\usbncm.inf
\Windows\INF\usbnet.inf
\Windows\INF\v_mscdsc.inf
\Windows\INF\wave.inf
\Windows\INF\wceisvista.inf
\Windows\INF\wdma_usb.inf
\Windows\INF\wdmaudio.inf
\Windows\INF\wfcvsc.inf
\Windows\INF\wfpcapture.inf
\Windows\INF\wgencounter.inf
\Windows\INF\wmbclass_wmc_union.inf
\Windows\INF\wnetvsc.inf
\Windows\INF\wnetvsc_vfpp.inf
\Windows\INF\ykinx64.inf
\Windows\System32\drivers\etc
\Windows\System32\drivers\acpipmi.sys
\Windows\System32\drivers\Acx01000.sys
\Windows\System32\drivers\afd.sys
\Windows\System32\drivers\agilevpn.sys
\Windows\System32\drivers\appid.sys
\Windows\System32\drivers\asyncmac.sys
\Windows\System32\drivers\bcmfn2.sys
\Windows\System32\drivers\beep.sys
\Windows\System32\drivers\bowser.sys
\Windows\System32\drivers\bridge.sys
\Windows\System32\drivers\bxvbda.sys
\Windows\System32\drivers\circlass.sys
\Windows\System32\drivers\cnghwassist.sys
\Windows\System32\drivers\csc.sys
\Windows\System32\drivers\dam.sys
\Windows\System32\drivers\drmk.sys
\Windows\System32\drivers\drmkaud.sys
\Windows\System32\drivers\evbda.sys
\Windows\System32\drivers\fdc.sys
\Windows\System32\drivers\flpydisk.sys
\Windows\System32\drivers\hidir.sys
\Windows\System32\drivers\http.sys
\Windows\System32\drivers\ibbus.sys
\Windows\System32\drivers\intelpep.sys
\Windows\System32\drivers\ipfltdrv.sys
\Windows\System32\drivers\ipnat.sys
\Windows\System32\drivers\kdnic.sys
\Windows\System32\drivers\lltdio.sys
\Windows\System32\drivers\mlx4_bus.sys
\Windows\System32\drivers\modem.sys
\Windows\System32\drivers\mrxdav.sys
\Windows\System32\drivers\mrxsmb.sys
\Windows\System32\drivers\mrxsmb20.sys
\Windows\System32\drivers\msgpiowin32.sys
\Windows\System32\drivers\mshidumdf.sys
\Windows\System32\drivers\mslldp.sys
\Windows\System32\drivers\ndfltr.sys
\Windows\System32\drivers\ndiscap.sys
\Windows\System32\drivers\NdisImPlatform.sys
\Windows\System32\drivers\NdisVirtualBus.sys
\Windows\System32\drivers\ndiswan.sys
\Windows\System32\drivers\Ndu.sys
\Windows\System32\drivers\NetAdapterCx.sys
\Windows\System32\drivers\net*.sys
\Windows\System32\drivers\nwifi.sys
\Windows\System32\drivers\pcmcia.sys
\Windows\System32\drivers\qwavedrv.sys
\Windows\System32\drivers\rasl2tp.sys
\Windows\System32\drivers\raspppoe.sys
\Windows\System32\drivers\rassstp.sys
\Windows\System32\drivers\rdpbus.sys
\Windows\System32\drivers\rdpdr.sys
\Windows\System32\drivers\rdpvideominiport.sys
\Windows\System32\drivers\rmcast.sys
\Windows\System32\drivers\RNDISMP.sys
\Windows\System32\drivers\rootmdm.sys
\Windows\System32\drivers\rspndr.sys
\Windows\System32\drivers\sbp2port.sys
\Windows\System32\drivers\scfilter.sys
\Windows\System32\drivers\sfloppy.sys
\Windows\System32\drivers\srv2.sys
\Windows\System32\drivers\srvnet.sys
\Windows\System32\drivers\tape.sys
\Windows\System32\drivers\tcpip.sys
\Windows\System32\drivers\tcpipreg.sys
\Windows\System32\drivers\terminpt.sys
\Windows\System32\drivers\TsUsbFlt.sys
\Windows\System32\drivers\TsUsbGD.sys
\Windows\System32\drivers\tsusbhub.sys
\Windows\System32\drivers\tunnel.sys
\Windows\System32\drivers\usb8023.sys
\Windows\System32\drivers\USBCAMD2.sys
\Windows\System32\drivers\usbcir.sys
\Windows\System32\drivers\vmgencounter.sys
\Windows\System32\drivers\vms3cap.sys
\Windows\System32\drivers\vwifibus.sys
\Windows\System32\drivers\vwififlt.sys
\Windows\System32\drivers\vwifimp.sys
\Windows\System32\drivers\wanarp.sys
\Windows\System32\drivers\WdiWiFi.sys
\Windows\System32\drivers\wfplwfs.sys
\Windows\System32\drivers\winmad.sys
\Windows\System32\drivers\winverbs.sys
\Windows\System32\DriverStore\FileRepository\athw8x.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\b57nd60a.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\bcmdhd64.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\bcmwdidhdpcie.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\bda.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\c_apo.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\c_avc.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\c_extension.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\c_image.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\c_linedisplay.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\c_media.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\c_modem.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\c_net.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\c_netclient.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\c_netdriver.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\c_netservice.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\c_nettrans.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\compositebus.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\dc21x4vm.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\e2xw10x64.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\gameport.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\intelpep.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\ipoib6x.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\kdnic.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\ks.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\kscaptur.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\ksfilter.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\lltdio.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\mchgr.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\mlx4_bus.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\modemcsa.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\mrvlpcie8897.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\msdri.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\mstape.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\msux64w10.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\mwlu97w8x64.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\ndiscap.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\ndisimplatform.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\ndisimplatformmp.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\ndisuio.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\net*.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\nulhpopr.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\nulhprs8.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\rdpbus.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\rdvgwddmdx11.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\rndiscmp.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\rspndr.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\rt640x64.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\rtux64w10.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\rtwlanu_oldic.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\tsusbhub.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\urschipidea.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\urssynopsys.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\usbcir.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\usbncm.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\usbnet.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\v_mscdsc.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\wave.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\wceisvista.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\wdma_usb.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\wdmaudio.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\wfcvsc.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\wfpcapture.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\wgencounter.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\wmbclass_wmc_union.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\wnetvsc.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\wnetvsc_vfpp.inf_amd64_*
\Windows\System32\DriverStore\FileRepository\ykinx64.inf_amd64_*

:end_files